#pragma once

#define CONFIG_MQTT_BUFFER_SIZE 1024
#define CONFIG_LIGHT_LED_MAX_COUNT 256
#define CONFIG_LIGHT_CONTROLLER WS2811
#define CONFIG_LIGHT_COLOR_KELVIN_INITIAL 2857
#define CONFIG_LIGHT_COLOR_KELVIN_WARM 2000
#define CONFIG_LIGHT_COLOR_KELVIN_COLD 7407
#define CONFIG_LIGHT_TRANSITION_COLOR 300

#ifndef CONFIG_LIGHT_PIN_CTL
#define CONFIG_LIGHT_PIN_CTL 25
#endif
